Settings:
  SnowToSpawn: true
  EnableWorld:
  - world
  - spawn

SnowToSpawn:
  Count: 15
  RadiusX: 10.0
  RadiusY: 10.0
  RadiusZ: 10.0

Messages:
  Help:
  - ''
  - '&2 Помощь по плагину &bCSnow &8| &2Текущая версия: &f%version%'
  - '&8 ▪ &b/csnow &f- помощь по плагину;'
  - '&8 ▪ &b/csnow reload &f- перезагрузить плагин.'
  - ''
  - '&2 Создатель: MishaNeYT (VK: @pleasantvkchannel)'
  - ''

  Reload: '&2Snow &8| &fПлагин успешно - &aперезагружен&f!'
  OnlyPlayer: '&2Snow &8| &cКоманду может использовать только игрок!'
  ErrorArgs: '&2Snow &8| &cКоманда введена не правильно! Используйте /csnow'
  noPerm: '&2Snow &8| &cУ вас нет прав!'





