Settings:
  TitlesOnJoin: true
  SnowToSpawn: true
TitlesOnJoin:
  Title: '&c&l2021!'
  Subtitle: '&eПоздравляю всех с новым годом!'
  FadeIn: 20
  Stay: 40
  FadeOut: 30
SnowToSpawn:
  Count: 25
  RadiusX: 15.0
  RadiusY: 30.0
  RadiusZ: 15.0
Messages:
  Help:
  - ''
  - '&2 Помощь по плагину &bCSnow &8| &2Текущая версия: &f%version%'
  - '&8 ▪ &b/csnow &f- помощь по плагину;'
  - '&8 ▪ &b/csnow reload &f- перезагрузить плагин.'
  - ''
  SnowOnOffUse: '&2Snow &8| &fИспользуйте: &e/csnow on &fили &e/csnow off&f.'
  SnowEnable: '&2Snow &8| &fУспешно - &aвключён&f!'
  SnowDisable: '&2Snow &8| &fУспешно - &cотключён&f!'
  Reload: '&2Snow &8| &fПлагин успешно - &aперезагружен&f!'
  noPerms: '&cУ вас нет прав!'